// <auto-generated />
using System;
using BaliBotDotNet.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaliBotDotNet.Migrations
{
    [DbContext(typeof(BaliBotDbContext))]
    partial class BaliBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("BaliBotDotNet.Models.AlternativeFact", b =>
                {
                    b.Property<int>("AlternativeFactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("AuthorID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AuthorID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AlternativeFactID");

                    b.HasIndex("AuthorID");

                    b.ToTable("AlternativeFact", (string)null);
                });

            modelBuilder.Entity("BaliBotDotNet.Models.Author", b =>
                {
                    b.Property<ulong>("AuthorID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AuthorID");

                    b.Property<bool>("IsQuotable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorID");

                    b.ToTable("Author", (string)null);
                });

            modelBuilder.Entity("BaliBotDotNet.Models.Message", b =>
                {
                    b.Property<ulong>("MessageID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MessageID");

                    b.Property<ulong>("AuthorID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AuthorID");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateSent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("GuildID");

                    b.HasKey("MessageID");

                    b.HasIndex("AuthorID");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("BaliBotDotNet.Models.Reminder", b =>
                {
                    b.Property<int>("ReminderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ReminderID");

                    b.Property<ulong>("AuthorID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AuthorID");

                    b.Property<ulong>("ChannelID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ChannelID");

                    b.Property<int>("IsReminderDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReminderText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReminderTime")
                        .HasColumnType("TEXT");

                    b.HasKey("ReminderID");

                    b.ToTable("Reminder", (string)null);
                });

            modelBuilder.Entity("BaliBotDotNet.Models.AlternativeFact", b =>
                {
                    b.HasOne("BaliBotDotNet.Models.Author", "Author")
                        .WithMany("AlternativeFacts")
                        .HasForeignKey("AuthorID")
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BaliBotDotNet.Models.Message", b =>
                {
                    b.HasOne("BaliBotDotNet.Models.Author", "Author")
                        .WithMany("Messages")
                        .HasForeignKey("AuthorID")
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BaliBotDotNet.Models.Author", b =>
                {
                    b.Navigation("AlternativeFacts");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
